### ISSUE TITLE
Implement a simple UI

### ISSUE THREAD

**Issue by Anders-E** [Anders-E/Ouija#21]
**Main menu**
- Join random session
- Join specific session
- Create private session

**In-game**
- Copy invite link
- Exit game session

**Notice:** no logic needed, only buttons and associated onClicks

**Comment by Anders-E** [comment]
https://stackoverflow.com/questions/16586734/html-over-the-canvas

**Comment by miht** [comment]
Idea: 
- Main menu
   - Join random session, join existing (using some token)
   - Settings (graphics, game, etc)
   - Credits at bottom

- Loading screen
   - Loading icon and text "Finding session"
   - Random fact in corner
   - Perhaps some image in middle

- Game view
   - Renderer and game viewport
   - Buttons (settings, leave session, about(?))
   - Event messages (player joins, player leaves, etc.)

![image](https://user-images.githubusercontent.com/11743680/59770958-289cbe00-92a9-11e9-803f-29cda9c12f1e.png)

**Comment by Anders-E** [comment]
Closed in #31
